#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

payload=$(mktemp /tmp/resource-check.XXXXXX)

cat > $payload <&0

# TODO

jq -n "${versions}" >&3
