#!/bin/sh
# vim: set ft=sh

set -e
test -z "$DEBUG" || set -x

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

payload=$(mktemp /tmp/resource-in.XXXXXX)

cat > "$payload" <&0

ami_id="$(jq -r '.version|.ImageId' < "$payload")"
region="$(jq -r '.version|.Region' < "$payload")"

export AWS_DEFAULT_REGION="$region"

# wait for image to be available
aws ec2 wait image-available --image-ids "$ami_id"

echo "$ami_id" > "$destination/id"
echo "$region" > "$destination/region"

# get some metadata
metadata=$(aws ec2 describe-images --image-ids "$ami_id" | \
    jq -r '.Images[0]|{Name,CreationDate,OwnerId}|to_entries|map({"name":.key, "value":.value})')

jq -n "{
  version: {ImageId: $(echo "$ami_id"| jq -R .)},
  metadata: $(echo "${metadata}"| jq .)
}" >&3
