#!/bin/sh

set -x

# awscli mock

if [ "$2" == "wait" ];then
    test "$5" == "ami-0123456" || exit 1
    sleep 1
    exit 0
fi

if [ "$2" == "describe-images" ];then
    test "$4" == "ami-0123456" || exit 1
    jq -n  '{Images: [{Name: "test", CreationDate: "2016-03-08T22:35:54.000Z", OwnerId:"1234"}]}'
    exit 0
fi

exit 1
