#!/usr/bin/env python

import sys
import os

# test existance of packer binary
assert os.path.exists('/usr/local/bin/packer')

log_lookup = {
    'src/ami.json': 'build-ami.log',
    'src/vars.json': 'build-vars.log',
}

if 'build' in sys.argv and '-machine-readable' in sys.argv:
    logfile = os.path.join(os.path.dirname(sys.argv[0]), log_lookup[sys.argv[-1]])
    print(open(logfile).read())
    sys.exit(0)

raise NotImplemented('passed arguments are not configured to return output.')


