#!/usr/bin/env python

import os
import sys

# test existance of packer binary
assert os.path.exists('/usr/local/bin/packer')

log_lookup = {
    'src/ami.json': 'build-ami.log',
    'src/build-vars.json': 'build-ami.log',
    'src/build-vars-from-file.json': 'build-ami.log',
}

print(sys.argv)

# test default arguments
assert 'build' in sys.argv
assert '-machine-readable' in sys.argv

template_file = sys.argv[-1]

# test argument passing
if template_file == 'src/build-vars.json':
    assert '-var=role=test' in sys.argv
if template_file == 'src/build-vars-from-file.json':
    assert '-var=source_ami=ami-12345678' in sys.argv

logfile = os.path.join(os.path.dirname(sys.argv[0]), log_lookup[template_file])
print(open(logfile).read())
sys.exit(0)

raise NotImplemented('passed arguments are not configured to return output.')
